### ISSUE TITLE
How can I test the production builds?

### ISSUE THREAD

**Issue by TheSisb** [aurelia/app-contacts#1]
I tried 'gulp build' and 'gulp prepare-release' but when I run 'gulp watch' or 'gulp serve' I'm still getting 140 network requests in Chrome.  Seems a little overkill for such a small demo so I wanted to see if it at least cleaned up well heh.

**Comment by EisenbergEffect** [comment]
Yes. We have a bundling solution we are currently working on. When that's done, there will be a new bundle task added to the gulp file and you will able to wrap it all up and deploy like that.

Basically, don't put this in production just yet... Consider Aurelia in an early preview stage. We have a lot more work to do over the next few months. Fortunately, bundling is at the top of the list and is already being worked on by one of our core team members. Hang in there and thanks for checking this out.

One other note...this repo isn't really finished yet. I started putting together the sample the other day but didn't get time to finish it. Once it's ready, I'll post some videos on it.
