### ISSUE TITLE
Error instantiating RouterView

### ISSUE THREAD

**Issue by omidkrad** [aurelia/app-contacts#13]
I tried building and running this app on two different computers (Windows 7 and 8.1) and on both of them I get the following error:

```
Uncaught Error: Error instantiating RouterView.
------------------------------------------------
inner error: TypeError: Cannot set property 'title' of undefined
    at App.configureRouter (http://localhost:9000/dist/app.js:25:26)
    at AppRouter.registerViewPort (http://localhost:9000/jspm_packages/github/aurelia/router@0.7.0/app-router.js:172:55)
    at new RouterView (http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.11.0/router-view.js:35:18)
    at Object.reflect.construct (http://localhost:9000/jspm_packages/github/zloirock/core-js@0.8.1/modules/es6.reflect.js:81:26)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.6.0/metadata.js:259:28)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.6.0/container.js:211:37)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.6.0/container.js:82:50)
    at Container.get [as superGet] (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.6.0/container.js:140:30)
    at Container.elementContainerGet [as get] (http://localhost:9000/jspm_packages/github/aurelia/templating@0.10.0/view-factory.js:27:17)
    at HtmlBehaviorResource.create (http://localhost:9000/jspm_packages/github/aurelia/templating@0.10.0/html-behavior.js:204:78)
```

I tried [these instructions](https://github.com/aurelia/skeleton-navigation/issues/77#issuecomment-94748710) to restore the jspm packages but that didn't fix it. Please help!

**Comment by omidkrad** [comment]
This was fixed. I don't know how, maybe [last commit](https://github.com/aurelia/app-contacts/commit/c4c8b9995b39bed3526100a4e0504e1047cc076f) fixed it?

**Comment by omidkrad** [comment]
Every time the build engine modifies the files under `./dest` directory the app stops working. I have to do a `git checkout ./dist` and refresh the browser for it to work again.

**Comment by omidkrad** [comment]
I lied, it's not fixed! after installing npm and jspm, when I run `git checkout ./dist` the app works. After that when I modify any source file, as soon as the corresponsing `.js` file under `dist` is updated the app stops working an I get the above `Error instantiating RouterView` error. So I can run the app with no modifications but cannot run it even if I just save a `.js` file with no changes that updates the compiled code under `dist`.

**Comment by omidkrad** [comment]
I'm pretty stuck on this issue. Can you please help me figure this out?

Here are the repro steps:
1. Clone the [app-contacts](https://github.com/aurelia/app-contacts) repository.
2. Install npm and jspm.
3. Run `gulp watch` and open the app in the browser.
4. Open `src/app.js` in Atom.
5. Save the file as is (don't make any changes).

App will refresh and hang on the `index.html` page, and in the browser's console you get: `Uncaught Error: Error instantiating RouterView.` (see [full error message](https://github.com/aurelia/app-contacts/issues/13#issue-70051872))

The output `dist/app.js` file is replaced with the following:

``` javascript
System.register(['./web-api'], function (_export) {
  var WebAPI, _classCallCheck, _createClass, App;

  return {
    setters: [function (_webApi) {
      WebAPI = _webApi.WebAPI;
    }],
    execute: function () {
      'use strict';

      _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } };

      _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ('value' in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

      App = (function () {
        function App(api) {
          _classCallCheck(this, App);

          this.api = api;
        }

        _createClass(App, [{
          key: 'configureRouter',
          value: function configureRouter(config, router) {
            config.title = 'Contacts';
            config.map([{ route: '', moduleId: 'no-selection', title: 'Select' }, { route: 'contacts/:id', moduleId: 'contact-detail' }]);

            this.router = router;
          }
        }], [{
          key: 'inject',
          value: [WebAPI],
          enumerable: true
        }]);

        return App;
      })();

      _export('App', App);
    }
  };
});
```

which is different from the original [`dist/app.js`](https://github.com/aurelia/app-contacts/blob/master/dist/app.js). Now if you do `git checkout ./dist` and refresh the browser, the app will run again.

**Comment by EisenbergEffect** [comment]
I really apologize for this. The problem is because the code in the contacts app has been updated for a not-yet-released version of the router. That's why it works at first. The dist folder contains code built with the current versions, but when you recompile the source, you get code built with a future version. This will resolve itself on Monday when we have the new set of releases. From that point on, I will do releases of the contacts app so that you can always have a released version that works.

**Comment by omidkrad** [comment]
No worries, Rob. I'm glad the fix is coming up.

**Comment by bsrdjan** [comment]
the same issue with just cloned and installed skeleton-navigation

**Comment by EisenbergEffect** [comment]
Yes, it's the same cause. Please use a released version. We will get this fixed in the next day or two.

**Comment by caperaven** [comment]
git clone https://github.com/aurelia/skeleton-navigation.git
npm install
jspm install -y

when I do this, I still get this error as described above.
I assume that using these commands does get the latest version or should I be doing something else?
I would love to get started with this, but having something that crashes from the beginning is not the best experience I have ever had.

If the above steps are right, then I will just need to wait, else if they are not please let me know what I need to change.

I believe the wait will be worth the while :)

**Comment by bsrdjan** [comment]
please check the reply from Rob, use the released version not latest master. I tested that and solved the problem.

**Comment by caperaven** [comment]
I don't really know how to do that, will have to google, that is why I asked if the steps were right. I just read the blog post so will try the jspm update and see what that does.
