### ISSUE TITLE
Contact list not being updated when contact is saved

### ISSUE THREAD

**Issue by vicentedealencar** [aurelia/app-contacts#2]
![image](https://cloud.githubusercontent.com/assets/1762868/5921172/47642b28-a629-11e4-8039-300ffd6fe317.png)

**Comment by EisenbergEffect** [comment]
Hey they partner! Thanks for checking this out. This particular sample isn't actually finished yet though ;) I just started putting it together the other day. So, I plan to address this and other issues..as well as some refactoring soon. Once it's done, I'll put together some videos on it too ;)

**Comment by kishorejangid** [comment]
This is a nice sample, I hope to get a complete sample where I can learn all about Aurelia.

**Comment by EisenbergEffect** [comment]
Fixed via the EA.
