### ISSUE TITLE
Problem when implementing undo behavior

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/app-contacts#20]
The contactDetail class uses a nice trick to check if the contact object has unsaved changes by storing the original value in this.originalContact:

```
 this.originalContact = JSON.parse(JSON.stringify(contact));
```

That works great, but imagine now I want to use the same approach for UNDO functionality.
Intuitively, one would restore the originalContact into the this.contact object when an undo is requested,

```
this.contact = this.originalContact;
```

 but that won't work, because this.contact is a much richer object compared to originalContact. Namely, this.contact contains the **observer** stuff: 
![image](https://cloud.githubusercontent.com/assets/4886272/9006485/0031550a-3788-11e5-878e-f42a7aa0bbe9.png)

whereas this.originalContact is kind of "naked" object:

![image](https://cloud.githubusercontent.com/assets/4886272/9006494/173b8d2e-3788-11e5-9534-e66268cced3b.png)

Suggestions for an elegant KISS solution welcome :)

**Comment by EisenbergEffect** [comment]
The correct way to do that would be to actually store the original contact as is, then data-bind/edit a copy. Then, on save, commit the copy's changes to the original. I'm not sure that this is in scope of this sample. Also, there are some data libraries, such as breeze.js, that affective have this built into their models.

**Comment by paulvanbladel** [comment]
It's not that simple.
I love breezeJs library and would definitely use Ward's library when needing sophisticated entity state tracking, here it's about a simple undo.
If I store a copy of the original retrieved contact, this.original = this.contact (so freshly retrieved from http service), that variable will not (yet) have the **observers** and **observer**, because these are added by the framework later on when the data binding machinery starts doing it's job.
So, as a result, when doing an UNDO and executing: this.contact = this.original, the this.contact is just a 'naked' object and databinding is lost.
Rob, forgive me if I'm raising this question (it's not an issue) probably at the wrong place, but the sample in this repository is very close to the feature I'm trying to work out correctly and I believe this feature is a genuine case for daily usage.
