### ISSUE TITLE
Can't get application running

### ISSUE THREAD

**Issue by alsoicode** [aurelia/app-contacts#23]
I'm dying to try Aurelia, but for the life of me, I can't get anything working. I've followed the instructions, and re-followed the instructions; installed dependencies and re-installed them, but all I get is:

![localhost](https://cloud.githubusercontent.com/assets/86738/10036803/b0a134b6-617a-11e5-921f-e668dbb47e32.jpg)

when I run:

```
gulp watch
```

and access: http://localhost:9000/

What am I doing wrong?

**Comment by EisenbergEffect** [comment]
I think it's a bit behind several releases. It's being tracked and we've got a PR to fix things up. I'll take care of that soon.
