### ISSUE TITLE
NProgress is not added to configuration by default

### ISSUE THREAD

**Issue by peterblazejewicz** [aurelia/app-contacts#3]
Whenever new installation is made the `config.js` is modified and rule for NProgress is added after runnin `jspm install`:

``` diff
diff --git a/config.js b/config.js
index e72be93..bae8674 100644
--- a/config.js
+++ b/config.js
@@ -96,6 +96,9 @@ System.config({
     "github:jspm/nodelibs-process@0.1.0": {
       "process": "npm:process@0.10.0"
     },
+    "github:rstacruz/nprogress@0.1.6": {
+      "css": "github:systemjs/plugin-css@0.1.0"
+    },
     "github:twbs/bootstrap@3.3.2": {
       "css": "github:systemjs/plugin-css@0.1.0",
       "jquery": "github:components/jquery@2.1.3"
```

Is this by jspm design or should it be added to repository file version?
Thanks!

**Comment by EisenbergEffect** [comment]
The config that I had checked in was generated with an older version of jspm, I believe. So, this should be ok. I'll update it all with the next series of releases.
