### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by hughgallagher** [aurelia/app-contacts#37]
Have just tried to do a simple install of app-contacts and get the following error on "npm install" ....

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

I am running supported versions of node, npm, and jspm.

Running on a high spec Windows machine. This did not happen a few days ago. Is there any changed code in the git repo that could cause this preoblem?

**Comment by EisenbergEffect** [comment]
Nothing changed.

**Comment by hughgallagher** [comment]
ok thanks...so I tried setting up the project from scratch using the tutorial on aurelia.io but after following the instructions and getting the aurelia core up and running the contact route app does nor watch:-

$ au run --watch
Starting 'readProjectConfiguration'...
{ uid: 3,
  name: 'readProjectConfiguration',
  branch: false,
  error:
   { [TypeError: Cannot read property 'replace' of undefined]
     domain:
      Domain {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        members: [] },
     domainThrown: true },
  duration: [ 0, 5136674 ],
  time: 1475685318838 }

**Comment by hughgallagher** [comment]
must have added in the json dependencies incorrectly. I started from scratch and it is working
