### ISSUE TITLE
Contact-manager not building

### ISSUE THREAD

**Issue by zakobyte** [aurelia/app-contacts#38]
Hi - I am trying to run the contact-manager on Mac OS 10.12. 

I get the following error

 au run --watch
/Users/name/a_aurelia_projects/contact-manager/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /Users/zak/a_aurelia_projects/contact-manager/node_modules/dev-ip/lib/dev-ip.js: 'return' outside of function (41:8)
  39 |     var out = getIp();
  40 |     if (!out.length) {

> 41 |         return console.log(messages.error);
>      |         ^
>   42 |     }
>   43 |     console.log(getIp("cli"));
>   44 | }
>     at Parser.pp.raise (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/location.js:22:13)
>     at Parser.pp.parseReturnStatement (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/statement.js:316:10)
>     at Parser.pp.parseStatement (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/statement.js:99:19)
>     at Parser.parseStatement (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/plugins/flow.js:28:22)
>     at Parser.pp.parseBlockBody (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/statement.js:516:21)
>     at Parser.pp.parseBlock (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/statement.js:497:8)
>     at Parser.pp.parseStatement (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/statement.js:119:19)
>     at Parser.parseStatement (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/plugins/flow.js:28:22)
>     at Parser.pp.parseIfStatement (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/statement.js:309:26)
>     at Parser.pp.parseStatement (/Users/zak/a_aurelia_projects/contact-manager/node_modules/babylon/lib/parser/statement.js:97:19)
> Zaks-MacBook-Air:contact-manager zak$

**Comment by EisenbergEffect** [comment]
Can you check your Node and NPM versions?
