### ISSUE TITLE
Filename error in aurelia_project/environements dir.

### ISSUE THREAD

**Issue by AJB99** [aurelia/app-contacts#39]
**I'm submitting a bug report**

* **Library Version:**
I honestly can't figure this out. Which of the 9 billion config files should I be looking in?

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
all

* **Language:**
all ESNext

**Current behavior:**
The `dev.js` file in the `aurelia_projects/environments` dir is erroneously named:
`
Starting 'configureEnvironment'...
{ uid: 8,
  name: 'configureEnvironment',
  branch: false,
  error: 
   { Error: File not found with singular glob: /Users/AJB/Server/Aurelia/contact-manager/aurelia_project/environments/development.js
...
`

**Expected/desired behavior:**
The tutorial should work.

* **What is the motivation / use case for changing the behavior?**
To make the tutorial work.

**Comment by EisenbergEffect** [comment]
You have a machine local environment variable named "development". That is why you are seeing this error. Try using this command `au run --watch --env dev`

**Comment by AJB99** [comment]
Thanks for the quick reply!

I actually _don't_ have a local ENV var named `development`, however the suggested command worked anyhow.
