### ISSUE TITLE
404 /src/aurelia-testing.js

### ISSUE THREAD

**Issue by AJB99** [aurelia/app-contacts#40]
**I'm submitting a bug report**

* **Library Version:**
Don't know.

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
all

* **Language:**
all ESNext

**Current behavior:**
http://localhost:9000/src/aurelia-testing.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Expected/desired behavior:**
I don't know yet, can't get through the basic tutorial.

* **What is the expected behavior?**
I don't know yet, can't get through the basic tutorial.

* **What is the motivation / use case for changing the behavior?**
I don't know yet, can't get through the basic tutorial.

**Comment by AJB99** [comment]
Changing `testing: true` to `testing:false` in the `src/environment.js` config file bypasses this bug.

**Comment by EisenbergEffect** [comment]
It sounds like something is wrong with your setup. Can you run `npm install` again and make sure you have everything?

**Comment by AJB99** [comment]
`npm install` produces no output. Seems like everything is up to date.

**Comment by AJB99** [comment]
The following is the output of `au run --watch --env dev`:

```
$ au run --watch --env dev
Starting 'readProjectConfiguration'...
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
Finished 'processMarkup'
Finished 'processCSS'
Finished 'configureEnvironment'
Starting 'buildJavaScript'...
Finished 'buildJavaScript'
Starting 'writeBundles'...
Tracing app...
Tracing environment...
Tracing main...
Tracing utility...
Tracing web-api...
Tracing resources/index...
Tracing app...
Tracing styles...
Tracing aurelia-binding...
Tracing aurelia-bootstrapper...
Tracing aurelia-dependency-injection...
Tracing aurelia-event-aggregator...
Tracing aurelia-framework...
Tracing aurelia-history...
Tracing aurelia-history-browser...
Tracing aurelia-loader-default...
Tracing aurelia-logging-console...
Tracing aurelia-router...
Tracing aurelia-templating-binding...
Tracing text...
Tracing aurelia-templating-resources...
Tracing aurelia-templating-router...
Tracing aurelia-testing...
Writing app-bundle.js...
Writing vendor-bundle.js...
Finished 'writeBundles'
Application Available At: http://localhost:9000
BrowserSync Available At: http://localhost:3001
Starting 'watch'...
```

**Comment by EisenbergEffect** [comment]
Can you zip up your solution (minus the node packages) and drop it here for me to look at? Something is odd here and I want to see if it's somehow an environment thing.

**Comment by jdanyow** [comment]
Couple other things for you to check:
- What do you see when you run `node -v` and `npm -v`?
- What happens if you delete your `node_modules` folder and then re-run `npm install`?

**Comment by AJB99** [comment]
@jdanyow 

```
$ node -v && npm -v
v6.6.0
3.10.3
```

Same issue after deleting `node_modules` and re-installing using both `npm install` and `sudo npm install`.

**Comment by AJB99** [comment]
[AU-Contact-Manager.zip](https://github.com/aurelia/app-contacts/files/601225/AU-Contact-Manager.zip)

**Comment by AJB99** [comment]
Hey folks, were you able to figure out where the issue may be?

**Comment by EisenbergEffect** [comment]
I think you just need to follow the tutorial further. The point that your code was at was an invalid state before completing the next few steps which are required to run.

**Comment by chrisprobst** [comment]
@EisenbergEffect Not sure what you mean with invalid state. But after creating a project with "au new" this bug still exists. Only solution is to turn off testing... hm.

**Comment by djensen47** [comment]
I'm also experiencing this bug. For me it seems to occur when I try to create and use a new environment. For instance, I have an environment called "mock." When I start with `au --env mock --watch` I never see `Tracing aurelia-testing...`

**Comment by djensen47** [comment]
It looks like my issue was that my new environment was not in the aurelia.json file for aurelia-testing 

```
          {
            "name": "aurelia-testing",
            "path": "../node_modules/aurelia-testing/dist/amd",
            "main": "aurelia-testing",
            "env": "dev & mock"
          }
```
