### ISSUE TITLE
'plugin.load' is undefined

### ISSUE THREAD

**Issue by AJB99** [aurelia/app-contacts#41]
**I'm submitting a bug report**

**library version**
latest

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.6

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
all

* **Language:**
all ESNext

**Current behavior:**
`TypeError: plugin.load is not a function. (In 'plugin.load(map.name, localRequire, load, config)', 'plugin.load' is undefined) vendor-bundle.js:4848`

**Expected/desired behavior:**
The function should be defined.

**Comment by EisenbergEffect** [comment]
WE need more information than this.

**Comment by AJB99** [comment]
What do you need?

That's all the out put I'm getting. I'm following the `contact-manager` tutorial _exactly_, this is the result.

**Comment by EisenbergEffect** [comment]
Where are you at in the tutorial? What is your CLI version?

**Comment by AJB99** [comment]
`au -v`: 0.22.0

I'm at "Building the application shell" part of the tutorial. Haven't been able to load the screen yet.

**Comment by EisenbergEffect** [comment]
I think this is related to the same as the other.

**Comment by joris-lambrechts** [comment]
I know this is closed, but I experienced the same problem after adding jquery & bootstrap to `aurelia.json`. Turns out that the changes to `aurelia.json` are not _watched_ when running with `au run --watch` . After re-running this, the `plugin.load` error is gone.
